on:
  push:
    branches:
    - master

permissions:
      id-token: write
      contents: read

jobs:
  DeployIAC:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
        enable-AzPSSession: true

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: eastus
        template: ./bicep/main.bicep
        parameters: 'ResourceGroupPrefix=vmss-workbook Location=EastUS'